## Primi passi

In questo primo notebook, farete i vostri primi passi con Python e controlleremoi potenziali del notebook. Alterneremo "box" (o "celle") di testo e celle di codice vuote, dove potrete scrivere codice e testarlo. Una cella può essere usata per scrivere testo (potete anche aggiungere formule come $\int_\sqrt{2}^\pi x\sin\left(\frac{1}{x}\right)dx$, usando linguaggio in $\LaTeX$) scegliendo "Testo" dal menu a tendina in cima alla scheda. Per eseguire una cella, premete `ctrl + enter`. Questo si applica anche a celle di testo formattato, come questa. Per modificarla, cliccateci due volte.

Il primo esempio di Python è un piccolo programma che assegna due numeri a due variabili, `p1` e` p2`, e stampa la loro somma.

```
p1 = 987654321
p2 = 123456789
print(p1 + p2)
```

Provate a scrivere le celle qui sopra nella box sotto, e premete `ctrl + enter`. Il risultato dovrebbe essere `1111111110`

In [1]:
p1 = 987654321
p2 = 123456789
print(p1 + p2)

1111111110


Le stringhe di testo possono essere formattate con la funzione `print`. Per stampare "La somma di 987654321 e 123456789 è 1111111110", scrivete

```
print(f"La somma di {p1} e {p2} è {p1 + p2}")
```

Notate l'`f` prima della stringa (`f` sta per "formattazione") e gli oggetti che vanno stampati rinchiusi fra parentesi graffe. Provate ora a stampare il prodotto di `p1` e `p2` qui sotto..

La somma di 987654321 e 123456789 è 1111111110


## Funzioni

Ora procediamo con un esempio per introdurre il flusso di lavoro. Supponiamo di voler determinare se un certo numero `n` è primo, ma, a differenza del precedente esempio, non conserviamo i suoi fattori. Lo pseudocodice è semplice: dobbiamo controllare, per ogni intero `k` da 2 a $\lfloor\sqrt{n}\rfloor$ (Vi ricordate perché?), se $\frac{n}{k}$ è intero, ovvero se la divisione restituisce un resto nullo.

```
Algorithm: PrimeNumber
Input: n
Output: 1 if n is prime, 0 otherwise
k = 2
while k <= sqrt(n):
  if n is divisible by k
    output 0
  increase k
output 1
```

L'implementazione Python è anch'essa molto semplice. Per incapsulare l'algoritmo, lo definiremo come una funzione di nome `PrimeNumber` che prende un numero come input e ritorna il valore di verità `True` se il numero è primo, e `False` altrimenti.

In [4]:
import math
def PrimeNumber(n):      # Definiamo la funzione PrimeNumber con un solo argomento n
    for k in range(2, math.floor(math.sqrt(n)) + 1): 
        if n % k == 0:   # Il simbolo "%" dà il resto della divisione intera n/k.
            return False
    return True

    
x = 13
if PrimeNumber(x):
    print(f"{x} è primo")
else:
    print(f"{x} non è primo")


13 è primo


Ora possiamo usare la definizione di `PrimeNumber` per ottenere tutti i numeri primi fra 2 e 1000. Ciò che dovete fare è costruire un loop invocando la funzione `PrimeNumber` prima di stampare il numero.

Provate a scrivere questo codice nel box qui sotto.

In [3]:
import math
def PrimeNumber(n):      # Definiamo la funzione PrimeNumber con un solo argomento n
    for k in range(2, math.floor(math.sqrt(n)) + 1): 
        if n % k == 0:   # Il simbolo "%" dà il resto della divisione intera n/k.
            return False
    return True

for i in range(2, 1000+1):
    if PrimeNumber(i):
        print(i)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997


Qualche nota sulla funzione `range`:
* range(10) risulta in tutti i numeri da 0 a 9;
* range(3,10) risulta in tutti i numeri da 3 a 9;
* range(3,100,7) risulta in tutti i numeri da 3 a 100 a step di 7, ovvero: 3, 10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87, 94.

Quindi, `range(n)` non include $n$, e si ferma immediatamente prima. Affinché il loop da 2 a $\sqrt{n}$ (o meglio, dato che necessitiamo di un intero, a $\lfloor\sqrt{n}\rfloor$) dobbiamo aumentare il limite di uno, per essere sicurə dobbiamo aumentare il limite di uno, assicurandoci di raggiungere il sopramenzionato valore di $\lfloor\sqrt{n}\rfloor$, da qui la funzione `math.floor(math.sqrt(n))+1`.

Avete notato?

* Niente punto e virgola (o semicolon, ";") alla fine di un'istruzione, come accade in C, C++, o Java;
* Nessuna parola chiave o indentazione per concludere un blocco. In Python, l'__indentazione__ è tutto: righe consecutive allo stesso livello di indentazione sono considerate un blocco, finire un'indentazione è equivalente a terminare un loop, per dire. Ad esempio, i due snippet seguenti fanno cose diverse:

```
for i in range(3):
   print(i)
   print(42)
```

```
for i in range(3):
   print(i)
print(42)
```

L'output del primo snippet sarà "0 42 1 42 2 42" (ogni numero su una nuova riga), mentre per il secondo sarà "0 1 2 42". Questa caratteristica di Python è unica e deve essere considerata ogni volta che si inizia a scrivere una nuova riga di istruzioni.

Potete controllare le compilazioni nel box qui sotto.

## Liste

Le liste sono una semplice struttura che immagazzina dati di possibilmente tipi diversi. Una lista contenente 1, 2, and "hey!" può essere dichiarata così:

```
l = [1,2,"hey!"]
```

Le liste possono essere concatenate con `+`:

```
l1 = [1,2,3]
l2 = [4,5,6]
print(l1 + l2)
```

Una lista è rappresentata con i suoi elementi separati da una virgola e chiusi tra parentesei quadre. Può essere inizializzata come lista vuota (`[]`) e poi popolata con un elemento alla volta, con il comando `append`. Lo snippet seguente:

```
l = []
for i in range(50, 55):
    l.append(i)

print(l)
```

risulterà nella lista `[50,51,52,53,54]`. Una lista può essere indicata, così come accade in molti altri linguaggi, con delle parentesi quadre, ma __notate__ che, in Python, gli indici iniziano con zero: quindi, il primo elemento nella lista di cui sopra, (50), ha indice 0 (`l[0]`). Indici negativi sono utilizzati per interrogare una lista dalla sua coda: `l[-1]` è 54, `l[-2]` è 53, e così via.

La particella `in` in Python può essere usata per controllare se un elemento appartiene ad una lista. Per esempio, se una lista è definita come `l = [2, 5, 88, 90909]`, allora `2 in l` restituisce `True`, mentre `44 in l` restituisce `False`. Indovinate cosa farà lo snippet seguente:

In [5]:
l1 = ['Paris', 'Toulouse', 'Milano', 'Torino', 'Roma', 'Munich', 'Frankfurt', 'Edinburgh']
l2 = ['Madrid', 'Paris', 'Berlin', 'Roma', 'Bruxelles', 'Bern', 'Wien']

for city1 in l1:
    if city1 in l2:
        print(city1)

Paris
Roma


## Comprensioni di lista

Le comprensioni di lista sono un potente strumento in Python per creare una lista implementando una condizione che la definisce. Per esempio, per definire un insieme, in linguaggio matematico, è possibile dire: $S = \{4i^3: i=3,4,\ldots{},10\}$. Questo è un modo compatto per definire l'insieme $\{108, 256, 500, 864, 1372, 2048, 2916, 4000\}$. In Python, questo può essere fatto in una singola riga di comando:

In [6]:
S = [4*i**3 for i in range(3,11)]
print(S)

[108, 256, 500, 864, 1372, 2048, 2916, 4000]


Qualche nota:
* `S` qui è una lista, non un insieme, quindi ogni elemento è associato ad una __posizione__ nella lista. Più in dettaglio, l'indice __non__ è legato al valore dell'`i` che ha generato quel numero:  `S[0] = 108`, `S[7] = 4000`, e `S[3] = 864`.
* Come prima, il comando `range(3,11)` è necessario per includere il valore di 10.
* L'operatore potenza si scrive `**`, ad es. `3**4` è 81.

Esercizio: sfidate Python a calcolare $2^{1000}$.

In [5]:
3**1000

1322070819480806636890455259752144365965422032752148167664920368226828597346704899540778313850608061963909777696872582355950954582100618911865342725257953674027620225198320803878014774228964841274390400117588618041128947815623094438061566173054086674490506178125480344405547054397038895817465368254916136220830268563778582290228416398307887896918556404084898937609373242171846359938695516765018940588109060426089671438864102814350385648747165832010614366132173102768902855220001

Le comprensioni di lista possono essere usate anche con predicati condizionali. In matematica, definiamo un insieme $S_1=\{2,\ldots{}, 100\}$ e definiamo un altro insieme $S_2$ con tutti i numeri primi contenuti in $S_1$. In Python, possiamo ottenere questo risultato con:

In [7]:
S1 = range(2,101)
S2 = [i for i in S1 if PrimeNumber(i)]
print(S2)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


Qui `S2` è definita come la lista di tutti gli `i` in `S1` tali per cui `PrimeNumber(i)` risulta in  `True`.

Nel prossimo notebook vedremo i dizionari di Python's, un'altra struttura dati che sarà estremamente utile nella restante parte dei laboratori.

Per esercitarvi, provate a scrivere una funzione che calcoli i primi 30 numeri di Fibonacci.  La sequenza di Fibonacci consiste di numeri  $(f_1, f_2, f_3, \ldots{})$ tali per cui $f_1 = f_2 = 1$ e $f_k = f_{k-1} + f_{k-2}$. Canonicamente, $f_1 = 1$.

In [10]:
def fib(x):
    if (x <= 2):
        return 1
    a = 1
    b = 1
    for i in range(x-2):
        tmp = a + b
        a = b
        b = tmp
    return b

print(fib(10))

55
